// Textes de l'interface en anglais : la clé est le texte français tel qu'il est écrit dans le code (voir t() dans langue.js).
// Fichier produit à partir des appels t() / tn() ; un texte absent reste en français et est signalé dans la console.

export const TEXTES = {
  "Guide": "Guide",
  "Rien dans le guide pour cette recherche.": "Nothing in the guide for this search.",
  "{n} section": "{n} section",
  "{n} sections": "{n} sections",
  "Impossible de charger les données": "Unable to load the data",
  "Vérifie que <code>serveur.py</code> est lancé et que <code>dates.json</code> se trouve à côté.": "Check that <code>serveur.py</code> is running and that <code>dates.json</code> is next to it.",
  "Frise": "Timeline",
  "Statistiques": "Statistics",
  "Données": "Data",
  "Rechercher dans les titres et descriptions": "Search titles and descriptions",
  "Rechercher dans le guide": "Search the guide",
  "Rechercher un évènement ou une année": "Search for an event or a year",
  "Enregistre d'abord les modifications, puis change de langue.": "Save your changes first, then switch language.",
  "Lecture seule": "Read-only",
  "Frise exportée de Cinabre le {date}": "Timeline exported from Cinabre on {date}",
  "Enregistrement…": "Saving…",
  "Modifications non enregistrées": "Unsaved changes",
  "Enregistré": "Saved",
  "Impossible de lister les frises : le serveur ne répond pas.": "Unable to list timelines: the server is not responding.",
  "{n} évènement": "{n} event",
  "{n} évènements": "{n} events",
  "Cette frise a des modifications non enregistrées.": "This timeline has unsaved changes.",
  "Enregistrer, puis continuer": "Save, then continue",
  "Continuer sans enregistrer": "Continue without saving",
  "Frises": "Timelines",
  "Nouvelle frise": "New timeline",
  "Nom de la frise": "Timeline name",
  "Créer": "Create",
  "Renommer cette frise": "Rename this timeline",
  "Renommer": "Rename",
  "Partager": "Share",
  "Une page HTML unique, en lecture seule (frise, statistiques, filtre, popups), qui s'ouvre dans un navigateur, sans Python ni serveur.": "A single read-only HTML page (timeline, statistics, filter, popups) that opens in a browser, without Python or a server.",
  "Elle est dans la langue actuelle de l'interface.": "It is in the current interface language.",
  "Exporter en page HTML": "Export as an HTML page",
  "Le serveur ne répond pas : vérifie qu'il est lancé.": "The server is not responding: check that it is running.",
  "L'enregistrement a échoué : voir le message en haut à droite.": "Saving failed: see the message at the top right.",
  "Page exportée : {nom}, dans le dossier des téléchargements.": "Page exported: {nom}, in your downloads folder.",
  "Elle inclut les modifications non enregistrées.": "It includes the unsaved changes.",
  "L'export a échoué : {erreur} Vérifie que le serveur est lancé.": "Export failed: {erreur} Check that the server is running.",
  "Indique un nom.": "Enter a name.",
  "Frise renommée. Enregistre (Ctrl+S) pour garder ce nom.": "Timeline renamed. Save (Ctrl+S) to keep this name.",
  "Clic : afficher uniquement cet élément, puis en ajouter ou en retirer d'autres. Alt + clic : l'isoler. Lieux et thèmes se combinent : Rome + Guerres montre les guerres de Rome.": "Click: show only this item, then add or remove others. Alt + click: isolate it. Places and themes combine: Rome + Wars shows the wars of Rome.",
  "Filtre": "Filter",
  "Tout afficher": "Show all",
  "Lieux": "Places",
  "Thèmes": "Themes",
  "Échelles": "Scales",
  "Aucun groupe pour l'instant : on les crée dans Données, onglet Groupes.": "No groups yet: create them in Data, Groups tab.",
  "<kbd>Alt</kbd> + clic : {action}": "<kbd>Alt</kbd> + click: {action}",
  "afficher seulement ce groupe": "show only this group",
  "afficher seulement ce thème": "show only this theme",
  "modifier dans Données": "edit in Data",
  "voir dans Données": "view in Data",
  "Important": "Important",
  "Lecture seule : les données se consultent mais ne se modifient pas.": "Read-only: the data can be browsed but not edited.",
  "Début d'époque": "Start of era",
  "Fin d'époque": "End of era",
  "Début de règne": "Start of reign",
  "★ Important": "★ Important",
  "de {debut} à {fin}": "from {debut} to {fin}",
  "à partir de {debut}": "from {debut}",
  "Époque": "Era",
  "Début provisoire, à vérifier": "Provisional start, to be checked",
  "Durée : {duree}": "Duration: {duree}",
  "Thème": "Theme",
  "Échelle": "Scale",
  "Lieu": "Place",
  "{n} élément": "{n} item",
  "{n} éléments": "{n} items",
  "{n} exemples tirés au hasard": "{n} examples picked at random",
  "Aucun élément pour l'instant.": "No items yet.",
  "Le serveur a répondu {n}.": "The server responded {n}.",
  "Évènements qui ne sont rattachés à aucun lieu.": "Events not attached to any place.",
  "Évènements et époques qui n'ont encore aucun thème.": "Events and eras that have no theme yet.",
  "aujourd'hui": "today",
  "Impossible de lire {chemin} (le serveur a répondu {n}).": "Unable to read {chemin} (the server responded {n}).",
  "Page d'origine inattendue : « {texte} » introuvable.": "Unexpected source page: “{texte}” not found.",
  "frise": "timeline",
  "Aller à": "Go to",
  "Nom": "Name",
  "début ou fin d'époque": "start or end of an era",
  "début de règne": "start of reign",
  "important": "important",
  "description au survol": "description on hover",
  "durée d'une époque": "duration of an era",
  "{n} date": "{n} date",
  "{n} dates": "{n} dates",
  "(filtrés)": "(filtered)",
  "Rien à afficher": "Nothing to show",
  "Aucun évènement de ces groupes. « Tout afficher », dans le panneau de gauche, retire le filtre.": "No events in these groups. “Show all”, in the left panel, removes the filter.",
  "Une frise toute neuve": "A brand-new timeline",
  "Pour commencer, créez vos groupes (lieux ou thèmes) puis vos premiers évènements dans l'onglet <a href=\"#donnees\">Données</a>. Le <a href=\"#aide\">Guide</a> explique pas à pas comment faire.": "To begin, create your groups (places or scales) and your first events in the <a href=\"#donnees\">Data</a> tab. The <a href=\"#aide\">Guide</a> explains how, step by step.",
  "Date approximative": "Approximate date",
  "jusqu'à {fin}": "until {fin}",
  "Repères": "Landmarks",
  "Début de la frise": "Start of the timeline",
  "Aujourd'hui": "Today",
  "Lignes spéciales": "Special lines",
  "Entrée pour y aller": "Enter to go there",
  "aucun résultat": "no results",
  "{i} sur {n}": "{i} of {n}",
  "1 milliard d'années": "1 billion years",
  "1 million d'années": "1 million years",
  "100 000 ans": "100,000 years",
  "An 0": "Year 0",
  "Exemples : {liste}": "Examples: {liste}",
  "Annuler la dernière modification (Ctrl+Z)": "Undo the last change (Ctrl+Z)",
  "Annuler": "Undo",
  "Coller plusieurs évènements ou époques d'un coup, une ligne chacun": "Paste several events or eras at once, one per line",
  "Ajouter plusieurs": "Add several",
  "Formulaire": "Form",
  "{n} source": "{n} source",
  "{n} sources": "{n} sources",
  "Cocher toutes les lignes affichées": "Tick all displayed rows",
  "Cocher cette ligne": "Tick this row",
  "Important : cliquer pour retirer l'étoile": "Important: click to remove the star",
  "Cliquer pour marquer comme important": "Click to mark as important",
  "début d'époque": "start of era",
  "fin d'époque": "end of era",
  "règne": "reign",
  "début déduit": "inferred start",
  "fin avant début": "end before start",
  "Ligne spéciale": "Special line",
  "Aucun groupe pour l'instant : « Ajouter un groupe », en haut à droite. Un groupe est un <b>lieu</b> (Rome, Chine…), ou une <b>échelle</b> (éon, ère…) pour les lignes spéciales.": "No groups yet: “Add a group”, top right. A group is a <b>place</b> (Rome, China…), or a <b>scale</b> (eon, era…) for special lines.",
  "L'ordre des groupes est celui du panneau de gauche et des colonnes d'époques de la frise. Un lieu peut être rangé dans un autre (sous-lieu) : choisir « Dans » dans son formulaire.": "The order of groups is the order of the left panel and of the era columns in the timeline. A place can be filed under another one (sub-place): choose “In” in its form.",
  "Monter": "Move up",
  "Descendre": "Move down",
  "Aucun thème pour l'instant : « Ajouter un thème », en haut à droite. Un thème classe les évènements par sujet (guerres, religion, sciences…), en plus de leur lieu.": "No themes yet: “Add a theme”, top right. A theme sorts events by subject (wars, religion, science…), in addition to their place.",
  "L'ordre des thèmes est celui du panneau de gauche. Un évènement peut avoir plusieurs thèmes.": "The order of themes is the order of the left panel. An event can have several themes.",
  "Débuts d'époque sans fin": "Era starts without an end",
  "À relier à leur fin pour devenir une époque (barre de durée dans la frise).": "To be linked to their end to become an era (duration bar in the timeline).",
  "Fins d'époque isolées": "Isolated era ends",
  "Souvent la fin d'un des débuts ci-dessus.": "Often the end of one of the starts above.",
  "Lignes spéciales à début déduit": "Special lines with an inferred start",
  "Début provisoire, à confirmer.": "Provisional start, to be confirmed.",
  "Évènements sans groupe": "Events without a group",
  "Ils apparaissent en gris dans la frise.": "They appear in grey in the timeline.",
  "Sans thème": "No theme",
  "Évènements et époques à classer dans au moins un thème.": "Events and eras to file under at least one theme.",
  "Dates non comprises": "Dates not understood",
  "Époques dont la fin précède le début": "Eras whose end precedes their start",
  "Doublons possibles": "Possible duplicates",
  "Même nom à plusieurs endroits.": "Same name in several places.",
  "Rien à vérifier.": "Nothing to check.",
  "Relier à une fin": "Link to an end",
  "Aucun évènement pour l'instant : « Ajouter un évènement », en haut à droite.": "No events yet: “Add an event”, top right.",
  "Aucune période pour l'instant : « Ajouter une période », en haut à droite.": "No periods yet: “Add a period”, top right.",
  "Aucun résultat": "No results",
  "pour cette recherche": "for this search",
  "avec ce filtre": "with this filter",
  "Modifications en cours : valide-les ou abandonne-les.": "Changes in progress: apply or discard them.",
  "Fermer": "Close",
  "Valider": "Apply",
  "Abandonner": "Discard",
  "Supprimer": "Delete",
  "Groupes <em>le premier donne la couleur du texte</em>": "Groups <em>the first gives the text colour</em>",
  "Thèmes <em>un ou plusieurs</em>": "Themes <em>one or more</em>",
  "Retirer ce thème": "Remove this theme",
  "Ajouter ce thème": "Add this theme",
  "Aucun thème : on les crée dans l'onglet Thèmes.": "No themes: create them in the Themes tab.",
  "Clic : en faire le groupe principal": "Click: make it the main group",
  "Groupe principal": "Main group",
  "Ajouter ce groupe": "Add this group",
  "principal": "main",
  "Retirer": "Remove",
  "Aucun groupe": "No group",
  "Faire de cet évènement une époque, avec une barre de durée jusqu'à sa fin": "Turn this event into an era, with a duration bar up to its end",
  "Relier à une fin…": "Link to an end…",
  "Nouvel évènement": "New event",
  "Évènement": "Event",
  "Date": "Date",
  "Approximative": "Approximate",
  "Début ou fin d'époque": "Start or end of an era",
  "Non": "No",
  "Description": "Description",
  "Sources <em>affichées quand la popup s'épingle (3 s de survol ou double-clic)</em>": "Sources <em>shown when the popup is pinned (3 s of hovering or double-click)</em>",
  "+ Ajouter une source": "+ Add a source",
  "Titre (ex. Wikipédia, Ancien Empire)": "Title (e.g. Wikipedia, Old Kingdom)",
  "Retirer cette source": "Remove this source",
  "Lien (https://…)": "Link (https://…)",
  "Citation": "Quote",
  "Nouvelle période": "New period",
  "Période": "Period",
  "Type": "Type",
  "Époque : barre de durée dans la colonne de son lieu": "Era: duration bar in the column of its place",
  "Ligne spéciale : éon, ère, période…": "Special line: eon, era, period…",
  "Sous-titre": "Subtitle",
  "Début": "Start",
  "Approximatif": "Approximate",
  "Fin": "End",
  "Début déduit, à vérifier": "Inferred start, to be checked",
  "Raccourci : Alt + clic sur la ligne": "Shortcut: Alt + click on the row",
  "Voir dans la frise": "Show in timeline",
  "En cas de suppression, ses {ev} et {p} passent dans": "If deleted, its {ev} and {p} move to",
  "{n} période": "{n} period",
  "{n} périodes": "{n} periods",
  "Nouveau groupe": "New group",
  "Groupe": "Group",
  "Description <em>ce qu'il couvre ; affichée au survol dans le panneau de gauche</em>": "Description <em>what it covers; shown on hover in the left panel</em>",
  "Couleur": "Colour",
  "Aperçu dans la frise": "Preview in the timeline",
  "Passer en thème sombre": "Switch to dark theme",
  "Passer en thème clair": "Switch to light theme",
  "Thème clair ou sombre": "Light or dark theme",
  "Choisir la couleur comme pour un fond blanc ; elle est adaptée au thème, clair ou sombre, à l'affichage.": "Choose the colour as for a white background; it is adapted to the theme, light or dark, when displayed.",
  "Crée une époque (barre de durée dans la frise) et retire cet évènement de la liste des dates.": "Creates an era (duration bar in the timeline) and removes this event from the list of dates.",
  "Nom de l'époque": "Name of the era",
  "Fin : un évènement du groupe {g} ou une date": "End: an event of the group {g} or a date",
  "Fin : un évènement ou une date": "End: an event or a date",
  "Autre date": "Other date",
  "fin": "end",
  "Aucun évènement plus tardif dans ce groupe.": "No later event in this group.",
  "Retirer aussi l'évènement de fin de la liste des dates": "Also remove the end event from the list of dates",
  "Retirer de toutes les lignes cochées": "Remove from all ticked rows",
  "Ajouter aux lignes cochées": "Add to the ticked rows",
  "(déjà sur {n})": "(already on {n})",
  "Modification en série": "Bulk edit",
  "<b>{n} évènement</b> coché": "<b>{n} event</b> ticked",
  "<b>{n} évènements</b> cochés": "<b>{n} events</b> ticked",
  "<b>{n} période</b> cochée": "<b>{n} period</b> ticked",
  "<b>{n} périodes</b> cochées": "<b>{n} periods</b> ticked",
  ", dont {n} masqué par la recherche ou le filtre": ", {n} of them hidden by the search or the filter",
  ", dont {n} masqués par la recherche ou le filtre": ", {n} of them hidden by the search or the filter",
  ", dont {n} masquée par la recherche ou le filtre": ", {n} of them hidden by the search or the filter",
  ", dont {n} masquées par la recherche ou le filtre": ", {n} of them hidden by the search or the filter",
  "Chaque changement s'applique tout de suite à toutes les lignes cochées ; <b>Annuler</b> le défait en une fois. Clic sur une ligne : la cocher ou la décocher ; Maj + clic : toute une plage. Au clavier : ↑ ↓ pour passer d'une ligne à l'autre, Espace pour la cocher ou la décocher.": "Each change applies immediately to all ticked rows; <b>Undo</b> reverts it in one go. Click a row: tick or untick it; Shift + click: a whole range. With the keyboard: ↑ ↓ to move from row to row, Space to tick or untick it.",
  "Groupes <em>clic : ajouter partout ; s'il est déjà partout, le retirer</em>": "Groups <em>click: add everywhere; if it is already everywhere, remove it</em>",
  "Aucun groupe : on les crée dans l'onglet Groupes.": "No groups: create them in the Groups tab.",
  "Dates approximatives": "Approximate dates",
  "Supprimer {n} évènement": "Delete {n} event",
  "Supprimer les {n} évènements": "Delete the {n} events",
  "Supprimer {n} période": "Delete {n} period",
  "Supprimer les {n} périodes": "Delete the {n} periods",
  "Tout décocher": "Untick all",
  "{nom} : retiré de {cible}.": "{nom}: removed from {cible}.",
  "{nom} : ajouté à {cible}.": "{nom}: added to {cible}.",
  "Vide : fin inconnue": "Empty: end unknown",
  "Date non comprise.": "Date not understood.",
  "Jusqu'à aujourd'hui": "Until today",
  "Année {a}": "Year {a}",
  "Nom du groupe": "Group name",
  "Confirmer la suppression": "Confirm deletion",
  "Indique une date.": "Enter a date.",
  "Évènement ajouté.": "Event added.",
  "Modification faite.": "Change made.",
  "Indique un début.": "Enter a start.",
  "Début non compris.": "Start not understood.",
  "Fin non comprise.": "End not understood.",
  "ou « aujourd'hui ».": "or “today”.",
  "La fin précède le début.": "The end precedes the start.",
  "Période ajoutée.": "Period added.",
  "« {nom} » est réservé.": "“{nom}” is reserved.",
  "Ce nom est déjà pris.": "This name is already taken.",
  "Groupe ajouté.": "Group added.",
  "Groupe renommé partout.": "Group renamed everywhere.",
  "Nouveau thème": "New theme",
  "{ev} et {p} ont ce thème.": "{ev} and {p} have this theme.",
  "Le renommer le change partout ; le supprimer le retire de tous, sans rien supprimer d'autre.": "Renaming it changes it everywhere; deleting it removes it from all of them, without deleting anything else.",
  "Ce thème existe déjà.": "This theme already exists.",
  "Thème ajouté.": "Theme added.",
  "Thème renommé partout.": "Theme renamed everywhere.",
  "Indique un nom pour l'époque.": "Enter a name for the era.",
  "Choisis la fin.": "Choose the end.",
  "Indique la date de fin ou choisis un évènement.": "Enter the end date or choose an event.",
  "Date de fin non comprise.": "End date not understood.",
  "Époque créée ; le début et la fin ont été retirés des dates.": "Era created; the start and the end were removed from the dates.",
  "Époque créée ; le début a été retiré des dates.": "Era created; the start was removed from the dates.",
  "Ajouter plusieurs éléments": "Add several items",
  "<p>Une ligne par évènement : <b>date | nom | groupes et thèmes | description</b></p>\n      <ul>\n        <li>Seuls la date et le nom sont obligatoires. Dans la 3e colonne, on met les lieux et les thèmes, séparés par des virgules.</li>\n        <li>« ~ » ou « vers » devant une date : date approximative.</li>\n        <li>Deux dates « début → fin » : une <b>époque</b>, avec sa barre de durée.</li>\n        <li>Les lignes vides et celles qui commencent par # sont ignorées.</li>\n        <li>On peut aussi coller du JSON : une liste d'objets <code>date</code>, <code>nom</code>, <code>groupes</code>, <code>description</code>,\n        et si besoin <code>themes</code>, <code>fin</code>, <code>approx</code>, <code>important</code>, <code>regne</code>, <code>limite</code>, <code>sources</code> ; <code>type</code> à <code>section</code> pour une ligne spéciale, avec <code>sous_titre</code>. C'est le format du bloc JSON de chaque fiche : on copie un élément d'une frise et on le colle ici, dans une autre.</li>\n      </ul>": "<p>One line per event: <b>date | name | groups and themes | description</b></p>\n      <ul>\n        <li>Only the date and the name are required. In the 3rd column, put places and themes, separated by commas.</li>\n        <li>“~”, “circa” or “about” before a date: approximate date.</li>\n        <li>Two dates “start → end”: an <b>era</b>, with its duration bar.</li>\n        <li>Empty lines and lines starting with # are ignored.</li>\n        <li>You can also paste JSON: a list of objects <code>date</code>, <code>name</code>, <code>groups</code>, <code>description</code>,\n        and if needed <code>themes</code>, <code>end</code>, <code>approx</code>, <code>important</code>, <code>reign</code>, <code>limit</code> (start or end), <code>sources</code>; <code>type</code> set to <code>section</code> for a special line, with <code>subtitle</code>. It is the format of the JSON block of each item: copy an item from one timeline and paste it here, in another.</li>\n      </ul>",
  "Exemple": "Example",
  "Modèle JSON": "JSON template",
  "Ajouter": "Add",
  "JSON illisible ({erreur}). Vérifie les virgules et les guillemets.": "Unreadable JSON ({erreur}). Check the commas and quotes.",
  "date manquante": "missing date",
  "date non comprise « {d} »": "date not understood “{d}”",
  "fin non comprise « {d} »": "end not understood “{d}”",
  "la fin précède le début": "the end precedes the start",
  "nom manquant": "missing name",
  "« {nom} » n'est ni un groupe ni un thème : corrige-le ou crée-le d'abord": "“{nom}” is neither a group nor a theme: fix it or create it first",
  "limite : « debut », « fin » ou rien": "limit: “start”, “end” or nothing",
  "existe déjà à cette date": "already exists at this date",
  "Ajouter {n} élément": "Add {n} item",
  "Ajouter {n} éléments": "Add {n} items",
  "Aperçu": "Preview",
  "{n} ligne à corriger": "{n} row to fix",
  "{n} lignes à corriger": "{n} rows to fix",
  "époque": "era",
  "Ligne {n} : {erreur}": "Line {n}: {erreur}",
  "Rien à ajouter : écris au moins une ligne.": "Nothing to add: write at least one line.",
  "Corrige d'abord les lignes en rouge.": "Fix the rows in red first.",
  "{n} élément ajouté. « Annuler » retire tout l'ajout d'un coup.": "{n} item added. “Undo” removes the whole addition at once.",
  "{n} éléments ajoutés. « Annuler » retire tout l'ajout d'un coup.": "{n} items added. “Undo” removes the whole addition at once.",
  "Groupes": "Groups",
  "Marques": "Marks",
  "Ordre": "Order",
  "Évènements": "Events",
  "Périodes": "Periods",
  "Ajouter un évènement": "Add an event",
  "Ajouter une période": "Add a period",
  "Ajouter un groupe": "Add a group",
  "Ajouter un thème": "Add a theme",
  "À vérifier": "To check",
  "Exemples": "Examples",
  "Sources": "Sources",
  "Évènements par tranche d'années": "Events per range of years",
  "{n} antérieur à {annee}, non compté": "{n} before {annee}, not counted",
  "{n} antérieurs à {annee}, non comptés": "{n} before {annee}, not counted",
  "{n} postérieur à 1999, non compté": "{n} after 1999, not counted",
  "{n} postérieurs à 1999, non comptés": "{n} after 1999, not counted",
  "Aucun évènement dans ces tranches avec ce filtre.": "No events in these ranges with this filter.",
  "Aucun évènement dans ces tranches pour l'instant : le graphique se remplira au fil des ajouts.": "No events in these ranges yet: the chart will fill up as you add them.",
  "tranches de {n} ans": "ranges of {n} years",
  "Nombre d'évènements par tranche d'années, empilés par groupe": "Number of events per range of years, stacked by group",
  "{debut} à {fin}": "{debut} to {fin}",
  "{n} dans la tranche, tous groupes affichés confondus. Clic : voir dans la frise.": "{n} in the range, all displayed groups combined. Click: show in the timeline.",
  "Enregistrer": "Save",
  "Chargement…": "Loading…",
  "Changer de frise ou en créer une": "Switch timeline or create one",
  "Onglets": "Tabs",
  "Langue de l'interface": "Interface language",
  "Filtre par groupe": "Filter by group",
  "Nom de frise invalide.": "Invalid timeline name.",
  "Cette frise n'existe plus.": "This timeline no longer exists.",
  "Indique un nom pour la nouvelle frise.": "Enter a name for the new timeline.",
  "Adresse inconnue": "Unknown address",
  "Données invalides, rien n'a été enregistré.": "Invalid data, nothing was saved.",
  "Sans groupe": "No group",
  "Étoile : ajoutée à {cible}.": "Star: added to {cible}.",
  "Étoile : retirée de {cible}.": "Star: removed from {cible}.",
  "Date approximative : ajoutée à {cible}.": "Approximate date: added to {cible}.",
  "Date approximative : retirée de {cible}.": "Approximate date: removed from {cible}.",
  "Dates approximatives : ajoutées à {cible}.": "Approximate dates: added to {cible}.",
  "Dates approximatives : retirées de {cible}.": "Approximate dates: removed from {cible}.",
  "Le fichier a été modifié ailleurs depuis son chargement. Recharge la page avant d'enregistrer.": "The file was changed elsewhere since it was loaded. Reload the page before saving.",
  "Demande invalide.": "Invalid request.",
  "Réglages": "Settings",
  "Dates précises": "Precise dates",
  "Une ligne par jour": "One line per day",
  "Chaque date a sa ligne : « 14 juil. 1789 », « 20 juil. 1789 »…": "Each date has its own line: “14 Jul 1789”, “20 Jul 1789”…",
  "Une ligne par mois": "One line per month",
  "Réglage propre à cette frise, enregistré dans son fichier (Ctrl+S) ; il ne change pas les dates.": "This setting belongs to this timeline and is saved in its file (Ctrl+S); it does not change the dates.",
  "Compris : {date}": "Understood: {date}",
  "{n} jour": "{n} day",
  "{n} jours": "{n} days",
  "{n} mois": "{n} months",
  "Une date peut être précise à l'année (1789), au mois (juillet 1789) ou au jour (14 juillet 1789). La frise peut montrer :": "A date can be precise to the year (1789), the month (July 1789) or the day (14 July 1789). The timeline can show:",
  "Une ligne par année": "One line per year",
  "Les évènements d'une même année sont côte à côte sur la ligne « 1789 », le jour et le mois écrits en petit devant le nom (« 14 juil. »).": "Events of the same year sit side by side on the “1789” line, with the day and month in small type before the name (“14 Jul”).",
  "Les évènements d'un même mois sont côte à côte sur la ligne « juil. 1789 », le jour écrit en petit devant le nom.": "Events of the same month sit side by side on the “Jul 1789” line, with the day in small type before the name.",
  "Une ligne spéciale qui commence en cours d'année ou de mois coupe la ligne en deux, pour rester à sa place.": "A special line that starts during the year or the month splits the line in two, to stay in its place.",
  "Par défaut.": "Default.",
  "Avec une ligne par jour, la date entière est sur la ligne : rien à écrire devant les noms.": "With one line per day, the whole date is on the line: nothing to write before the names.",
  "Ce que la ligne ne montre pas peut être écrit en petit devant le nom de chaque évènement :": "What the line does not show can be written in small type before the name of each event:",
  "Rien": "Nothing",
  "Le mois": "The month",
  "Le jour et le mois": "The day and month",
  "Le jour": "The day",
  "« juil. Prise de la Bastille »": "“Jul Storming of the Bastille”",
  "« 14 juil. Prise de la Bastille »": "“14 Jul Storming of the Bastille”",
  "« 14 Prise de la Bastille »": "“14 Storming of the Bastille”",
  "Détail des dates dans les évènements": "Date detail in events",
  "Dates aux nombreux évènements": "Dates with many events",
  "Passer à la ligne": "Wrap onto new lines",
  "Quand les évènements d'une date ne tiennent pas sur une ligne, la ligne continue en dessous ; le nombre par ligne dépend de la largeur de l'écran. Par défaut.": "When the events of a date do not fit on one line, the line continues below; the number per line depends on the screen width. Default.",
  "Toujours sur une seule ligne": "Always on a single line",
  "Les évènements rétrécissent pour tenir sur la ligne ; les noms sont raccourcis (…), complets au survol.": "Events shrink to fit on the line; names are shortened (…), in full on hover.",
  "Rappel des lignes spéciales": "Special line reminder",
  "En haut de la frise, les lignes spéciales que l'on vient de dépasser restent affichées :": "At the top of the timeline, the special lines you have just scrolled past stay displayed:",
  "Brièvement": "Briefly",
  "Chaque ligne reste une dizaine de lignes après son passage, puis la frise la pousse vers le haut. Par défaut.": "Each line stays for about ten lines after it is passed, then the timeline pushes it up. Default.",
  "Jusqu'à la suivante de même niveau": "Until the next one of the same level",
  "On voit toujours l'éon, l'ère, la période… en cours : chaque ligne spéciale reste jusqu'à la suivante de même niveau, ou jusqu'à sa fin si elle en a une.": "You always see the current eon, era, period…: each special line stays until the next one of the same level, or until its end if it has one.",
  "Le niveau d'une ligne spéciale est son groupe de type échelle : dans l'onglet Groupes, la première échelle de la liste est le niveau le plus large, les suivantes de plus en plus fines (flèches ↑ ↓ pour les réordonner).": "The level of a special line is its group of type scale: in the Groups tab, the first scale in the list is the broadest level, the next ones finer and finer (arrows ↑ ↓ to reorder them).",
  "niveau {n}": "level {n}",
  "Afficher le filtre": "Show the filter",
  "Masquer le filtre": "Hide the filter",
  "Un filtre est actif": "A filter is active",
  "Une saisie n'est pas valide : corrige-la avant de changer de ligne, ou Échap pour l'abandonner.": "An entry is not valid: fix it before changing row, or press Esc to discard it.",
  "Données, Réglages : plages d'années et durée des tranches": "Data, Settings: ranges of years and length of the ranges",
  "Changer les tranches": "Change the ranges",
  "{n} postérieur à {annee}, non compté": "{n} after {annee}, not counted",
  "{n} postérieurs à {annee}, non comptés": "{n} after {annee}, not counted",
  "{n} entre deux plages, non compté": "{n} between two ranges, not counted",
  "{n} entre deux plages, non comptés": "{n} between two ranges, not counted",
  "par année": "per year",
  "Réglages propres à cette frise, enregistrés dans son fichier (Ctrl+S) ; ils ne changent pas les dates.": "Settings of this timeline, saved in its file (Ctrl+S); they do not change the dates.",
  "De": "From",
  "à": "to",
  "par tranches de": "in steps of",
  "ans": "years",
  "Retirer cette plage": "Remove this range",
  "Le graphique compte les évènements par tranche d'années. Par défaut : de la première date de la frise (au plus tôt - 5 000) à la dernière, en tranches de 1, 5, 10, 25, 100, 500 ou 1 000 ans, la plus fine qui ne donne pas plus de 80 barres. On peut définir ses propres plages, chacune avec la durée de ses tranches (par exemple 500 ans pour l'Antiquité, 1 an pour une révolution).": "The chart counts events per range of years. By default: from the first date of the timeline (5000 BC at the earliest) to the last, in ranges of 1, 5, 10, 25, 100, 500 or 1,000 years, the finest that gives no more than 80 bars. You can define your own spans, each with the length of its ranges (for example 500 years for Antiquity, 1 year for a revolution).",
  "Aucune date pour l'instant.": "No dates yet.",
  "Réglage par défaut.": "Default setting.",
  "{n} tranche": "{n} range",
  "{n} tranches": "{n} ranges",
  "+ Ajouter une plage": "+ Add a span",
  "Revenir au réglage par défaut": "Back to the default setting",
  "La durée des tranches doit être un nombre entier d'années.": "The length of the ranges must be a whole number of years.",
  "Les plages doivent se suivre sans se chevaucher.": "Spans must follow each other without overlapping.",
  "Trop de tranches (plus de {n}) : allonge leur durée ou réduis les plages.": "Too many ranges (more than {n}): lengthen them or shorten the spans.",
  "Jeu": "Game",
  "La frise qui se construit": "The timeline that builds itself",
  "tous": "all",
  "Un premier évènement est posé, avec sa date. Les suivants arrivent un par un, sans date : place chacun au bon endroit dans la frise qui se construit. Une erreur coûte une vie ({n} en tout) ; l'évènement est alors posé à sa vraie place.": "A first event is laid down, with its date. The next ones arrive one by one, without a date: put each one in the right place in the timeline as it builds. A mistake costs a life ({n} in all); the event is then laid at its true place.",
  "Années": "Years",
  "Les lieux et les thèmes en jeu sont ceux du filtre, dans le panneau de gauche.": "The places and themes in play are those of the filter, in the left panel.",
  "le début": "the start",
  "la fin": "the end",
  "Montrer les descriptions": "Show the descriptions",
  "Commencer": "Start",
  "Année non comprise : écris par exemple « - 500 », « 1453 » ou « 45k ».": "Year not understood: write for example “-500”, “1453” or “45k”.",
  "Pas assez d'évènements avec ce filtre et ces années : élargis-les.": "Not enough events with this filter and these years: widen them.",
  "Pas assez d'évènements datés dans ces années.": "Not enough dated events in these years.",
  "{n} évènement en jeu": "{n} event in play",
  "{n} évènements en jeu": "{n} events in play",
  "À placer": "To place",
  "Vies restantes": "Lives left",
  "{n} bien placé": "{n} well placed",
  "{n} bien placés": "{n} well placed",
  "{n} restant": "{n} left",
  "{n} restants": "{n} left",
  "Placer ici": "Place here",
  "✓ Bien placé": "✓ Well placed",
  "✗ Mal placé : le voici à sa place": "✗ Misplaced: here it is at its place",
  "Tout est placé !": "Everything is placed!",
  "Partie terminée.": "Game over.",
  "{n} évènement bien placé": "{n} event well placed",
  "{n} évènements bien placés": "{n} events well placed",
  "{n} erreur": "{n} mistake",
  "{n} erreurs": "{n} mistakes",
  "Rejouer": "Play again",
  "Changer les réglages": "Change the settings",
  "Pas de jeu": "No game",
  "Afficher l'onglet Jeu": "Show the Game tab",
  "« La frise qui se construit » : replacer un à un des évènements de la frise dans l'ordre. Aussi dans les pages exportées de cette frise.": "“The timeline that builds itself”: put events of the timeline back in order, one by one. Also in the exported pages of this timeline.",
  "Arrêter la partie": "Stop the game",
  "Date masquée": "Hidden date",
  "Noms trop longs": "Names too long",
  "Plus de {n} caractères : ils sont tronqués dans la frise ; la suite peut aller dans la description.": "Over {n} characters: they are cut short in the timeline; the rest can go in the description.",
  "{n} caractère": "{n} character",
  "{n} caractères": "{n} characters",
  "et ses sous-lieux": "and its sub-places",
  "Replier ses sous-lieux": "Collapse its sub-places",
  "Déplier ses {n} sous-lieux": "Expand its {n} sub-places",
  "Lieu, dans {parent}": "Place, in {parent}",
  "{n} sous-lieu compris": "{n} sub-place included",
  "{n} sous-lieux compris": "{n} sub-places included",
  "Sous-lieu de {parent}": "Sub-place of {parent}",
  "{n} sous-lieu": "{n} sub-place",
  "{n} sous-lieux": "{n} sub-places",
  "Dans": "In",
  "Premier niveau : ce lieu contient {n}.": "Top level: this place contains {n}.",
  "Dans <em>facultatif : en faire un sous-lieu d'un autre lieu</em>": "In <em>optional: make it a sub-place of another place</em>",
  "Aucun : premier niveau": "None: top level",
  "Sous-lieux": "Sub-places",
  "Un lieu peut être rangé dans un autre (onglet Groupes, champ « Dans ») : « France » dans « Europe ». Dans le panneau de gauche, les sous-lieux sont :": "A place can be filed under another one (Groups tab, “In” field): “France” in “Europe”. In the left panel, sub-places are:",
  "Dépliés": "Expanded",
  "En retrait sous leur lieu, toujours visibles. Par défaut.": "Indented under their place, always visible. Default.",
  "Repliés sous leur lieu": "Collapsed under their place",
  "Une flèche devant le lieu les montre ou les cache. Pratique avec beaucoup de lieux.": "An arrow in front of the place shows or hides them. Handy with many places.",
  "Avec des sous-lieux, les barres sont empilées :": "With sub-places, bars are stacked:",
  "Par lieu de premier niveau": "By top-level place",
  "Un sous-lieu compte dans la couleur de son lieu (« France » dans « Europe ») : peu de couleurs, plus lisible. Par défaut.": "A sub-place counts in the colour of its place (“France” in “Europe”): few colours, easier to read. Default.",
  "Par sous-lieu": "By sub-place",
  "Chaque lieu, quel que soit son niveau, a sa part de la barre, dans sa couleur.": "Every place, whatever its level, has its own share of the bar, in its colour.",
  "{n} époque sans barre": "{n} era without a bar",
  "{n} époques sans barre": "{n} eras without a bar",
  "Pas assez de place pour toutes les barres d'époques : les époques marquées ★, puis les plus longues, passent en premier. Les autres gardent leur pastille ; filtrer un lieu les fait apparaître.": "Not enough room for every era bar: eras marked ★, then the longest ones, come first. The others keep their label; filtering a place brings them back.",
  "JSON <em>pour copier l'élément dans une autre frise</em>": "JSON <em>to copy this item into another timeline</em>",
  "Modifier le JSON modifie l'élément. Pour le reprendre dans une autre frise : Copier, puis, dans l'autre frise, « Ajouter plusieurs » et coller.": "Editing the JSON edits the item. To reuse it in another timeline: Copy, then, in the other timeline, “Add several” and paste.",
  "Pour reprendre cet élément dans une frise : Copier, puis, dans la frise, « Ajouter plusieurs » et coller.": "To reuse this item in a timeline: Copy, then, in that timeline, “Add several” and paste.",
  "Un seul élément ici, sous la forme { … }. Pour en ajouter plusieurs : « Ajouter plusieurs ».": "Only one item here, written { … }. To add several: “Add several”.",
  "Avec une fin ou un type, c'est une période : à coller dans l'onglet Périodes, « Ajouter plusieurs ».": "With an end or a type, it is a period: paste it in the Periods tab, “Add several”.",
  "Copier": "Copy",
  "Copié": "Copied",
  "Copier en JSON": "Copy as JSON",
  "À coller dans « Ajouter plusieurs » d'une autre frise": "To paste into “Add several” of another timeline",
  "ligne spéciale": "special line",
  "{n} autre élément à vérifier est masqué par le filtre ou la recherche ({total} en tout).": "{n} more item to check is hidden by the filter or the search ({total} in all).",
  "{n} autres éléments à vérifier sont masqués par le filtre ou la recherche ({total} en tout).": "{n} more items to check are hidden by the filter or the search ({total} in all).",
};
